In [1]:
# Importando bibliotecas
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib as plt

# Base Desmatamento

In [70]:
# Importar a base sobre desmatamento
df_desmatamento = pd.read_csv('desmatamento_ucs.csv', encoding='latin1', sep=";")

In [71]:
# Exibindo as primeiras 5 linhas do "df_desmatamento"
df_desmatamento

,cnuc,uc,biocgfun,prodes,2021,2020,2019,2018,2017,2016,...,2008,2007,2006,2005,2004,2003,2002,2001,2000,1997
0,0000.00.0001,APA Anhatomirim,Marinho-Costeiro,Não,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0000.00.0002,APA Cavernas do Peruaçu,Cerrado,Sim,"41,8698","25,9009","8,686","27,0174","90,3144","15,5474",...,"127,8657","127,8657","1455,18475","1455,18475","1442,04345","1442,04345","823,97995","823,97995","7048,5908",0
2,0000.00.0003,APA da Bacia do Rio Descoberto,Cerrado,Sim,"29,4815","16,9189","6,1382","34,8262","47,261","27,5458",...,"60,666","60,666","133,0672","133,0672","424,46005","424,46005","35,2013","35,2013","24411,3688",0
3,0000.00.0004,APA da Bacia do Rio São Bartolomeu,Cerrado,Sim,"81,5854","75,1749","80,5036","185,9016","65,1662","32,8627",...,"114,38775","114,38775","521,3432","521,3432","1970,2341","1970,2341","110,89395","110,89395","40247,2264",0
4,0000.00.0005,APA da Bacia do Rio São João - Mico-Leão-Dourado,Mata Atlântica,Não,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
320,0000.00.3410,PARNA do Acari,Amazônia,Sim,"8,0403","193,3631","3,835","7,3076","14,0984",0,...,0,0,0,0,0,0,0,0,0,0
321,0000.00.3411,REBIO do Manicoré,Amazônia,Sim,"21,3202","6,4048",0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
322,0000.00.3432,REVIS do Arquipélago de Alcatrazes,Marinho-Costeiro,Não,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
323,0000.00.3519,PARNA dos Campos Ferruginosos,Amazônia,Sim,"1,9271",0,"197,0321","26,8094","13,1762","105,0862",...,0,0,0,0,0,0,0,0,0,0
324,0000.00.3693,RESEX Baixo Rio Branco-Jauaperi,Amazônia,Sim,"14,33",0,0,"7,1987",0,0,...,0,0,0,0,0,0,0,0,0,0

In [72]:
df_desmatamento.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 325 entries, 0 to 324
Data columns (total 27 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   cnuc      325 non-null    object
 1   uc        325 non-null    object
 2   biocgfun  325 non-null    object
 3   prodes    325 non-null    object
 4   2021      325 non-null    object
 5   2020      325 non-null    object
 6   2019      325 non-null    object
 7   2018      325 non-null    object
 8   2017      325 non-null    object
 9   2016      325 non-null    object
 10  2015      325 non-null    object
 11  2014      325 non-null    object
 12  2013      325 non-null    object
 13  2012      325 non-null    object
 14  2011      325 non-null    object
 15  2010      325 non-null    object
 16  2009      325 non-null    object
 17  2008      325 non-null    object
 18  2007      325 non-null    object
 19  2006      325 non-null    object
 20  2005      325 non-null    object
 21  2004      325 non-null    object
 22  2003      325 non-null    object
 23  2002      325 non-null    object
 24  2001      325 non-null    object
 25  2000      325 non-null    object
 26  1997      325 non-null    object
dtypes: object(27)
memory usage: 68.7+ KB

In [73]:
# Como a coluna "cnuc" não tem informação relevante, excluiremos da base.
df_desmatamento = df_desmatamento.drop("cnuc",axis=1)
df_desmatamento.head()

,uc,biocgfun,prodes,2021,2020,2019,2018,2017,2016,2015,...,2008,2007,2006,2005,2004,2003,2002,2001,2000,1997
0,APA Anhatomirim,Marinho-Costeiro,Não,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,APA Cavernas do Peruaçu,Cerrado,Sim,"41,8698","25,9009","8,686","27,0174","90,3144","15,5474","95,8332",...,"127,8657","127,8657","1455,18475","1455,18475","1442,04345","1442,04345","823,97995","823,97995","7048,5908",0
2,APA da Bacia do Rio Descoberto,Cerrado,Sim,"29,4815","16,9189","6,1382","34,8262","47,261","27,5458","15,1121",...,"60,666","60,666","133,0672","133,0672","424,46005","424,46005","35,2013","35,2013","24411,3688",0
3,APA da Bacia do Rio São Bartolomeu,Cerrado,Sim,"81,5854","75,1749","80,5036","185,9016","65,1662","32,8627","100,6799",...,"114,38775","114,38775","521,3432","521,3432","1970,2341","1970,2341","110,89395","110,89395","40247,2264",0
4,APA da Bacia do Rio São João - Mico-Leão-Dourado,Mata Atlântica,Não,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [74]:
# Em algumas linhas não foram coletado dados. Veja a linha de índice 0:
display(df_desmatamento.iloc[0])

uc           APA Anhatomirim
biocgfun    Marinho-Costeiro
prodes                   Não
2021                       0
2020                       0
2019                       0
2018                       0
2017                       0
2016                       0
2015                       0
2014                       0
2013                       0
2012                       0
2011                       0
2010                       0
2009                       0
2008                       0
2007                       0
2006                       0
2005                       0
2004                       0
2003                       0
2002                       0
2001                       0
2000                       0
1997                       0
Name: 0, dtype: object

In [76]:
# Coletando os índices das linhas onde na coluna "prodes" existe valor "Não" e obedece demais comparações
index_names = df_desmatamento[ ((df_desmatamento['prodes'] == 'Não') & (df_desmatamento['2018'] == '12,5858')) | ((df_desmatamento['prodes'] == 'Não') & (df_desmatamento['2021'] == '33,4555')) | ((df_desmatamento['prodes'] == 'Não') & (df_desmatamento['2021'] == '3,2901'))].index
index_names

Index([130, 310, 311], dtype='int64')

In [77]:
# Exibindo as linhas do dataframe com base na lista de índices gerados
display(df_desmatamento.iloc[index_names])

# Exportei para verificar a quantidade linhas quando 'prodes' == 'Não'. Apenas 3 e com quase nenhuma coleta.
#prodes_Nao = df_desmatamento.iloc[index_names]
#prodes_Nao.to_excel("prodes_Nao.xlsx")

,uc,biocgfun,prodes,2021,2020,2019,2018,2017,2016,2015,...,2008,2007,2006,2005,2004,2003,2002,2001,2000,1997
130,PARNA Cavernas do Peruaçu,Cerrado,Não,0,0,0,"12,5858",0,0,0,...,0,0,0,0,0,0,0,0,0,0
310,ESEC Alto Maués,Amazônia,Não,"33,4555","5,3021","45,7996",0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
311,RESEX Marinha Mocapajuba,Marinho-Costeiro,Não,"3,2901",0,"3,5927",0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [78]:
df_3linhas = df_desmatamento.iloc[index_names]
df_3linhas

,uc,biocgfun,prodes,2021,2020,2019,2018,2017,2016,2015,...,2008,2007,2006,2005,2004,2003,2002,2001,2000,1997
130,PARNA Cavernas do Peruaçu,Cerrado,Não,0,0,0,"12,5858",0,0,0,...,0,0,0,0,0,0,0,0,0,0
310,ESEC Alto Maués,Amazônia,Não,"33,4555","5,3021","45,7996",0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
311,RESEX Marinha Mocapajuba,Marinho-Costeiro,Não,"3,2901",0,"3,5927",0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [79]:
# Coletando os índices das linhas onde na coluna "prodes" existe valor "Não"
index_names = df_desmatamento[df_desmatamento['prodes'] == 'Não'].index
index_names

Index([  0,   4,   5,   6,   7,   8,   9,  10,  12,  13,
       ...
       305, 306, 307, 308, 309, 310, 311, 315, 316, 322],
      dtype='int64', length=153)

In [80]:
# Excluiremos as linhas com base no filtro anterior
df_desmatamento.drop(index_names, inplace = True)
df_desmatamento

,uc,biocgfun,prodes,2021,2020,2019,2018,2017,2016,2015,...,2008,2007,2006,2005,2004,2003,2002,2001,2000,1997
1,APA Cavernas do Peruaçu,Cerrado,Sim,"41,8698","25,9009","8,686","27,0174","90,3144","15,5474","95,8332",...,"127,8657","127,8657","1455,18475","1455,18475","1442,04345","1442,04345","823,97995","823,97995","7048,5908",0
2,APA da Bacia do Rio Descoberto,Cerrado,Sim,"29,4815","16,9189","6,1382","34,8262","47,261","27,5458","15,1121",...,"60,666","60,666","133,0672","133,0672","424,46005","424,46005","35,2013","35,2013","24411,3688",0
3,APA da Bacia do Rio São Bartolomeu,Cerrado,Sim,"81,5854","75,1749","80,5036","185,9016","65,1662","32,8627","100,6799",...,"114,38775","114,38775","521,3432","521,3432","1970,2341","1970,2341","110,89395","110,89395","40247,2264",0
11,APA Serra da Tabatinga,Cerrado,Sim,"699,9801","368,4614","1115,9382","2518,3705","432,0308","14,8942","411,0192",...,"3084,51825","3084,51825","872,9935","872,9935","1726,06465","1726,06465","1247,33605","1247,33605","9970,4472",0
18,APA Delta do Parnaíba,Marinho-Costeiro,Sim,"342,8655","549,8499","639,233","893,9644","502,0757","527,7738","660,758",...,"1730,6215","1730,6215","997,1394","997,1394","2091,41335","2091,41335","1186,1437","1186,1437","4751,2088",0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319,FLONA do Aripuanã,Amazônia,Sim,"395,4864","93,2029","735,6052","208,0321","197,465","38,1676","31,0824",...,0,0,0,0,0,0,0,0,0,0
320,PARNA do Acari,Amazônia,Sim,"8,0403","193,3631","3,835","7,3076","14,0984",0,0,...,0,0,0,0,0,0,0,0,0,0
321,REBIO do Manicoré,Amazônia,Sim,"21,3202","6,4048",0,0,0,0,"27,0818",...,0,0,0,0,0,0,0,0,0,0
323,PARNA dos Campos Ferruginosos,Amazônia,Sim,"1,9271",0,"197,0321","26,8094","13,1762","105,0862",0,...,0,0,0,0,0,0,0,0,0,0
324,RESEX Baixo Rio Branco-Jauaperi,Amazônia,Sim,"14,33",0,0,"7,1987",0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [81]:
#  Juntar (ou combinar) dois DataFrames com as mesmas colunas no Pandas usando a função concat.
df_desmatamento = pd.concat([df_desmatamento, df_3linhas], ignore_index=True)
df_desmatamento

,uc,biocgfun,prodes,2021,2020,2019,2018,2017,2016,2015,...,2008,2007,2006,2005,2004,2003,2002,2001,2000,1997
0,APA Cavernas do Peruaçu,Cerrado,Sim,"41,8698","25,9009","8,686","27,0174","90,3144","15,5474","95,8332",...,"127,8657","127,8657","1455,18475","1455,18475","1442,04345","1442,04345","823,97995","823,97995","7048,5908",0
1,APA da Bacia do Rio Descoberto,Cerrado,Sim,"29,4815","16,9189","6,1382","34,8262","47,261","27,5458","15,1121",...,"60,666","60,666","133,0672","133,0672","424,46005","424,46005","35,2013","35,2013","24411,3688",0
2,APA da Bacia do Rio São Bartolomeu,Cerrado,Sim,"81,5854","75,1749","80,5036","185,9016","65,1662","32,8627","100,6799",...,"114,38775","114,38775","521,3432","521,3432","1970,2341","1970,2341","110,89395","110,89395","40247,2264",0
3,APA Serra da Tabatinga,Cerrado,Sim,"699,9801","368,4614","1115,9382","2518,3705","432,0308","14,8942","411,0192",...,"3084,51825","3084,51825","872,9935","872,9935","1726,06465","1726,06465","1247,33605","1247,33605","9970,4472",0
4,APA Delta do Parnaíba,Marinho-Costeiro,Sim,"342,8655","549,8499","639,233","893,9644","502,0757","527,7738","660,758",...,"1730,6215","1730,6215","997,1394","997,1394","2091,41335","2091,41335","1186,1437","1186,1437","4751,2088",0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170,PARNA dos Campos Ferruginosos,Amazônia,Sim,"1,9271",0,"197,0321","26,8094","13,1762","105,0862",0,...,0,0,0,0,0,0,0,0,0,0
171,RESEX Baixo Rio Branco-Jauaperi,Amazônia,Sim,"14,33",0,0,"7,1987",0,0,0,...,0,0,0,0,0,0,0,0,0,0
172,PARNA Cavernas do Peruaçu,Cerrado,Não,0,0,0,"12,5858",0,0,0,...,0,0,0,0,0,0,0,0,0,0
173,ESEC Alto Maués,Amazônia,Não,"33,4555","5,3021","45,7996",0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
174,RESEX Marinha Mocapajuba,Marinho-Costeiro,Não,"3,2901",0,"3,5927",0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

# Base Espécies

In [5]:
# Importar a base sobre espécies
df_especies = pd.read_csv('pda-especies_ameacadas.csv', encoding='latin1', sep=";")
df_especies.head()

,Reino,Filo,Classe,Ordem,Família,Gênero,Nome Científico,Autor,Nome Comum,Grupo,Categoria,Consta em Lista Nacional Oficial,Estado,Região,Bioma,Bacia Hidrográfica,Unidade de Conservação Federal,Unidade de Conservação Estadual,RPPN
0,Animalia,Chordata,Actinopterygii,Characiformes,Parodontidae,Apareiodon,Apareiodon davisi,"Fowler, 1941",Peixe-rei,Peixes Continentais,Em Perigo,Sim,"Ceará, Paraíba, Pernambuco, Rio Grande do Norte",Nordeste,"Caatinga, Mata Atlântica",Sub-bacia Jaguaribe\nSub-bacia Litoral CE PB\n...,NaN,NaN,NaN
1,Animalia,Chordata,Actinopterygii,Characiformes,Characidae,Myleus,Myloplus tiete,"(Eigenmann & Norris, 1900)",Pacu-prata,Peixes Continentais,Em Perigo,Sim,"Goiás, Mato Grosso do Sul, Minas Gerais, Paran...","Centro-Oeste, Sudeste, Sul","Cerrado, Mata Atlântica",Sub-bacia Grande\nSub-bacia Paranaíba\nSub-bac...,NaN,NaN,NaN
2,Animalia,Chordata,Actinopterygii,Characiformes,Characidae,Brycon,Brycon devillei,"(Castelnau, 1855)",Piabinha,Peixes Continentais,Em Perigo,Sim,"Bahia, Minas Gerais","Nordeste, Sudeste","Cerrado, Mata Atlântica",Sub-bacia Doce\nSub-bacia Jequitinhonha,NaN,NaN,NaN
3,Animalia,Chordata,Actinopterygii,Characiformes,Characidae,Bryconamericus,Bryconamericus lambari,"Malabarba & Kindel, 1995",Lambari,Peixes Continentais,Em Perigo,Sim,Rio Grande do Sul,Sul,Mata Atlântica,Sub-bacia Guaíba,NaN,NaN,NaN
4,Animalia,Chordata,Actinopterygii,Characiformes,Characidae,Diapoma,Diapoma pyrrhopteryx,"Menezes & Weitzman, 2011",Lambari,Peixes Continentais,Em Perigo,Sim,"Rio Grande do Sul, Santa Catarina",Sul,"Mata Atlântica, Pampa",Sub-bacia Uruguai Alto\nSub-bacia Uruguai Médio,NaN,NaN,NaN

In [7]:
df_especies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1257 entries, 0 to 1256
Data columns (total 19 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Reino                             1257 non-null   object
 1   Filo                              1256 non-null   object
 2   Classe                            1256 non-null   object
 3   Ordem                             1256 non-null   object
 4   Família                           1256 non-null   object
 5   Gênero                            1256 non-null   object
 6   Nome Científico                   1256 non-null   object
 7   Autor                             1244 non-null   object
 8   Nome Comum                        1031 non-null   object
 9   Grupo                             1256 non-null   object
 10  Categoria                         1256 non-null   object
 11  Consta em Lista Nacional Oficial  1256 non-null   object
 12  Estado                            1139 non-null   object
 13  Região                            1139 non-null   object
 14  Bioma                             1221 non-null   object
 15  Bacia Hidrográfica                1081 non-null   object
 16  Unidade de Conservação Federal    118 non-null    object
 17  Unidade de Conservação Estadual   68 non-null     object
 18  RPPN                              58 non-null     object
dtypes: object(19)
memory usage: 186.7+ KB

In [16]:
# Filtro para saber se cada entradas na coluna 'Unidade de Conservação Estadual' não é nula
df_especies['Unidade de Conservação Estadual'].notnull()

0       False
1       False
2       False
3       False
4       False
        ...
1252    False
1253    False
1254    False
1255    False
1256    False
Name: Unidade de Conservação Estadual, Length: 1257, dtype: bool

In [19]:
# Exibindo as linhas da base "df_especies" onde a coluna 'Unidade de Conservação Estadual' não é nula. Baseado no filtro anterior.
df_especies[df_especies['Unidade de Conservação Estadual'].notnull()].head()

,Reino,Filo,Classe,Ordem,Família,Gênero,Nome Científico,Autor,Nome Comum,Grupo,Categoria,Consta em Lista Nacional Oficial,Estado,Região,Bioma,Bacia Hidrográfica,Unidade de Conservação Federal,Unidade de Conservação Estadual,RPPN
475,Animalia,Chordata,Aves,Accipitriformes,Accipitridae,Morphnus,Morphnus guianensis,"(Daudin, 1800)","gavião-real-falso, uiraçu, uiraçu-falso",Aves,Vulnerável,Sim,"Acre, Amapá, Amazonas, Bahia, Espírito Santo, ...","Centro-Oeste, Nordeste, Norte, Sudeste, Sul","Amazônia, Cerrado, Mata Atlântica",Sub-bacia Araguaia\nSub-bacia Doce\nSub-bacia ...,"APA Guaraqueçaba, ESEC de Maracá, FLONA Carajá...",ÁREA DE PROTEÇÃO AMBIENTAL ILHA DO BANANAL/CAN...,"Estação Veracel, RPPN Laço de Amor, RPPN Lote ..."
485,Animalia,Chordata,Aves,Galliformes,Cracidae,Aburria,Aburria cujubi,"(Pelzeln, 1858)","cajubi, cajubim, coxovi, cujubi, cujubim, jacu...",Aves,Vulnerável,Sim,"Amazonas, Goiás, Maranhão, Mato Grosso, Mato G...","Centro-Oeste, Nordeste, Norte","Amazônia, Cerrado, Pantanal",Sub-bacia Araguaia\nSub-bacia Foz Amazonas\nSu...,"FLONA Itaituba II, PARNA Campos Amazônicos, PA...",ÁREA DE PROTEÇÃO AMBIENTAL DA CHAPADA DOS GUIM...,"RPPN Fazenda Estância Dorochê, RPPN Jubran, RP..."
504,Animalia,Chordata,Aves,Psittaciformes,Psittacidae,Anodorhynchus,Anodorhynchus leari,"Bonaparte, 1856",arara-azul-de-lear,Aves,Em Perigo,Sim,Bahia,Nordeste,Caatinga,Sub-bacia Itapecuru-Paraguaçu\nSub-bacia Litor...,ESEC Raso da Catarina,ÁREA DE PROTEÇÃO AMBIENTAL SERRA BRANCA / RASO...,NaN
518,Animalia,Chordata,Aves,Passeriformes,Rhynchocyclidae,Cnipodectes,Cnipodectes superrufus,"Lane, Servat, Valqui & Lambert, 2007",flautim-rufo,Aves,Vulnerável,Sim,Acre,Norte,Amazônia,Sub-bacia Purus,ESEC Rio Acre,ÁREA DE PROTEÇÃO AMBIENTAL IGARAPÉ SÃO FRANCISCO,NaN
523,Animalia,Chordata,Aves,Passeriformes,Thamnophilidae,Hypocnemis,Hypocnemis ochrogyna,"Zimmer, 1932",cantador-ocráceo,Aves,Vulnerável,Sim,"Mato Grosso, Rondônia","Centro-Oeste, Norte","Amazônia, Cerrado, Pantanal",Sub-bacia Araguaia\nSub-bacia Madeira\nSub-bac...,"ESEC da Serra das Araras, PARNA Campos Amazôni...","PARQUE ESTADUAL SERRA RICARDO FRANCO, RESERVA ...","RPPN Água Boa, RPPN Jubran, RPPN Seringal Assu..."

In [20]:
# Contando a frequência de valores que aparecem na coluna "Unidade de Conservação Estadual"
df_especies['Unidade de Conservação Estadual'].value_counts()

Unidade de Conservação Estadual
ÁREA DE PROTEÇÃO AMBIENTAL DO LAGO DE TUCURUI                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            5
APA SAPUCAí MIRIM                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        2
ÁREA DE PROTEÇÃO AMBIENTAL ILHA DO BANANAL/CANTÃO                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        2
ÁREA DE PROTEçãO AMBIENTAL DE UPAON-AçU / MIRITIBA / ALTO PREGUIçAS                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      2
ESTAÇÃO ECOLÓGICA DE ÁGUAS EMENDADAS                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ..
ÁREA DE PROTEÇÃO AMBIENTAL LAGOA ENCANTADA, ÁREA DE PROTEÇÃO AMBIENTAL SANTO ANTÔNIO                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     1
APA CAMPOS DO JORDÃO, APA PLANALTO DO TURVO, APA RIO PARDINHO E RIO VERMELHO, APA SAPUCAí MIRIM, APA SERRA DO MAR, APA SISTEMA CANTAREIRA, ÁREA DE PROTEÇÃO AMBIENTAL DO BANHADO GRANDE, ÁREA DE PROTEÇÃO AMBIENTAL ESTADUAL DA ESCARPA DEVONIANA, ÁREA DE PROTEÇÃO AMBIENTAL ESTADUAL DA SERRA DA ESPERANÇA, ÁREA DE PROTEÇÃO AMBIENTAL FERNÃO DIAS, ÁREA DE PROTEçãO AMBIENTAL ROTA DO SOL, PARQUE ESTADUAL DA CANTAREIRA, PARQUE ESTADUAL DA SERRA DO TABULEIRO, PARQUE ESTADUAL DE CAMPOS DO JORDÃO, PARQUE ESTADUAL DE ESPIGãO ALTO, PARQUE ESTADUAL DO PAPAGAIO-CHARãO, PARQUE ESTADUAL DO RIO DOCE, PARQUE ESTADUAL DO RIO TURVO, PARQUE ESTADUAL INTERVALES, PARQUE ESTADUAL RIO CANOAS, PARQUE ESTADUAL SERRA DO BRIGADEIRO, PARQUE ESTADUAL SERRA DO PAPAGAIO, PARQUE ESTADUAL TURÍSTICO DO ALTO DO RIBEIRA    1
ÁREA DE PROTEÇÃO AMBIENTAL DE MURICÍ, ÁREA DE PROTEÇÃO AMBIENTAL DE SIRINHAÉM, ÁREA DE PROTEÇÃO AMBIENTAL SERRA DO SABONETAL, PARQUE ESTADUAL DO RIO DOCE, REFúGIO DE VIDA SILVESTRE MATAS DO SISTEMA GURJAú                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             1
ÁREA DE PROTEÇÃO AMBIENTAL SANTO ANTÔNIO                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 1
ÁREA DE PROTEÇÃO AMBIENTAL ÁGUAS VERTENTES, PARQUE ESTADUAL PICO DO ITAMBÉ, PARQUE ESTADUAL SERRA DO INTENDENTE, PARQUE NATURAL MUNICIPAL DO TABULEIRO                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   1
Name: count, Length: 61, dtype: int64

In [23]:
# Exibindo as linhas da base "df_especies" onde a coluna 'Unidade de Conservação Federal' não é nula. Baseado no filtro anterior.
df_especies[df_especies['Unidade de Conservação Federal'].notnull()].head()

,Reino,Filo,Classe,Ordem,Família,Gênero,Nome Científico,Autor,Nome Comum,Grupo,Categoria,Consta em Lista Nacional Oficial,Estado,Região,Bioma,Bacia Hidrográfica,Unidade de Conservação Federal,Unidade de Conservação Estadual,RPPN
58,Animalia,Chordata,Actinopterygii,Perciformes,Lutjanidae,Lutjanus,Lutjanus cyanopterus,"(Cuvier, 1828)","Caranha, Vermelho-caranho, Caranha-do-fundo, C...",Peixes Marinhos,Vulnerável,Sim,NaN,NaN,Marinho,NaN,ESEC Carijós,NaN,NaN
475,Animalia,Chordata,Aves,Accipitriformes,Accipitridae,Morphnus,Morphnus guianensis,"(Daudin, 1800)","gavião-real-falso, uiraçu, uiraçu-falso",Aves,Vulnerável,Sim,"Acre, Amapá, Amazonas, Bahia, Espírito Santo, ...","Centro-Oeste, Nordeste, Norte, Sudeste, Sul","Amazônia, Cerrado, Mata Atlântica",Sub-bacia Araguaia\nSub-bacia Doce\nSub-bacia ...,"APA Guaraqueçaba, ESEC de Maracá, FLONA Carajá...",ÁREA DE PROTEÇÃO AMBIENTAL ILHA DO BANANAL/CAN...,"Estação Veracel, RPPN Laço de Amor, RPPN Lote ..."
479,Animalia,Chordata,Aves,Pelecaniformes,Ardeidae,Tigrisoma,Tigrisoma fasciatum,"(Such, 1825)","socó-boi-escuro, socó-jararaca",Aves,Vulnerável,Sim,"Amapá, Amazonas, Goiás, Mato Grosso, Mato Gros...","Centro-Oeste, Norte, Sudeste, Sul","Amazônia, Cerrado, Mata Atlântica, Pantanal",Sub-bacia Amapá Litoral\nSub-bacia Araguaia\nS...,FLONA Amazonas,NaN,NaN
481,Animalia,Chordata,Aves,Passeriformes,Rhynchocyclidae,Phylloscartes,Phylloscartes beckeri,"Gonzaga & Pacheco, 1995",borboletinha-baiana,Aves,Em Perigo,Sim,"Bahia, Minas Gerais","Nordeste, Sudeste","Caatinga, Mata Atlântica",Sub-bacia Contas\nSub-bacia Itapecuru-Paraguaç...,"PARNA Alto Cariri, REBIO da Mata Escura",NaN,NaN
485,Animalia,Chordata,Aves,Galliformes,Cracidae,Aburria,Aburria cujubi,"(Pelzeln, 1858)","cajubi, cajubim, coxovi, cujubi, cujubim, jacu...",Aves,Vulnerável,Sim,"Amazonas, Goiás, Maranhão, Mato Grosso, Mato G...","Centro-Oeste, Nordeste, Norte","Amazônia, Cerrado, Pantanal",Sub-bacia Araguaia\nSub-bacia Foz Amazonas\nSu...,"FLONA Itaituba II, PARNA Campos Amazônicos, PA...",ÁREA DE PROTEÇÃO AMBIENTAL DA CHAPADA DOS GUIM...,"RPPN Fazenda Estância Dorochê, RPPN Jubran, RP..."

In [21]:
# Contando a frequência de valores que aparecem na coluna "Unidade de Conservação Federal"
df_especies['Unidade de Conservação Federal'].value_counts()

Unidade de Conservação Federal
REBIO do Gurupi                                                       5
FLONA Caxiuanã                                                        5
APA Serra da Mantiqueira                                              3
FLONA do Tapajós                                                      3
FLONA do Tapajós, FLONA Jamanxim                                      2
                                                                     ..
FLONA Caxiuanã, FLONA Trairão, PARNA Amazônia                         1
FLONA Carajás, FLONA do Tapajós, FLONA Itaituba II, PARNA Amazônia    1
RESEX Tapajós-Arapiuns                                                1
FLONA Tapirape-Aquiri, REBIO Tapirapé                                 1
APA do Morro da Pedreira, PARNA da Serra do Cipó                      1
Name: count, Length: 99, dtype: int64

In [24]:
# Como analisaremos a nível Federal, excluiremos a coluna "Unidade de Conservação Estadual"
df_especies = df_especies.drop("Unidade de Conservação Estadual",axis=1)
df_especies.head()

,Reino,Filo,Classe,Ordem,Família,Gênero,Nome Científico,Autor,Nome Comum,Grupo,Categoria,Consta em Lista Nacional Oficial,Estado,Região,Bioma,Bacia Hidrográfica,Unidade de Conservação Federal,RPPN
0,Animalia,Chordata,Actinopterygii,Characiformes,Parodontidae,Apareiodon,Apareiodon davisi,"Fowler, 1941",Peixe-rei,Peixes Continentais,Em Perigo,Sim,"Ceará, Paraíba, Pernambuco, Rio Grande do Norte",Nordeste,"Caatinga, Mata Atlântica",Sub-bacia Jaguaribe\nSub-bacia Litoral CE PB\n...,NaN,NaN
1,Animalia,Chordata,Actinopterygii,Characiformes,Characidae,Myleus,Myloplus tiete,"(Eigenmann & Norris, 1900)",Pacu-prata,Peixes Continentais,Em Perigo,Sim,"Goiás, Mato Grosso do Sul, Minas Gerais, Paran...","Centro-Oeste, Sudeste, Sul","Cerrado, Mata Atlântica",Sub-bacia Grande\nSub-bacia Paranaíba\nSub-bac...,NaN,NaN
2,Animalia,Chordata,Actinopterygii,Characiformes,Characidae,Brycon,Brycon devillei,"(Castelnau, 1855)",Piabinha,Peixes Continentais,Em Perigo,Sim,"Bahia, Minas Gerais","Nordeste, Sudeste","Cerrado, Mata Atlântica",Sub-bacia Doce\nSub-bacia Jequitinhonha,NaN,NaN
3,Animalia,Chordata,Actinopterygii,Characiformes,Characidae,Bryconamericus,Bryconamericus lambari,"Malabarba & Kindel, 1995",Lambari,Peixes Continentais,Em Perigo,Sim,Rio Grande do Sul,Sul,Mata Atlântica,Sub-bacia Guaíba,NaN,NaN
4,Animalia,Chordata,Actinopterygii,Characiformes,Characidae,Diapoma,Diapoma pyrrhopteryx,"Menezes & Weitzman, 2011",Lambari,Peixes Continentais,Em Perigo,Sim,"Rio Grande do Sul, Santa Catarina",Sul,"Mata Atlântica, Pampa",Sub-bacia Uruguai Alto\nSub-bacia Uruguai Médio,NaN,NaN

In [25]:
df_especies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1257 entries, 0 to 1256
Data columns (total 18 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Reino                             1257 non-null   object
 1   Filo                              1256 non-null   object
 2   Classe                            1256 non-null   object
 3   Ordem                             1256 non-null   object
 4   Família                           1256 non-null   object
 5   Gênero                            1256 non-null   object
 6   Nome Científico                   1256 non-null   object
 7   Autor                             1244 non-null   object
 8   Nome Comum                        1031 non-null   object
 9   Grupo                             1256 non-null   object
 10  Categoria                         1256 non-null   object
 11  Consta em Lista Nacional Oficial  1256 non-null   object
 12  Estado                            1139 non-null   object
 13  Região                            1139 non-null   object
 14  Bioma                             1221 non-null   object
 15  Bacia Hidrográfica                1081 non-null   object
 16  Unidade de Conservação Federal    118 non-null    object
 17  RPPN                              58 non-null     object
dtypes: object(18)
memory usage: 176.9+ KB

In [ ]:
df_especies_sem_null = df_especies.dropna(subset='Unidade de Conservação Federal')
df_especies_sem_null = df_especies_sem_null[['Nome Científico', 'Nome Comum', 'Categoria', 'Estado', 'Região', 'Unidade de Conservação Federal']]
df_especies_sem_null.at[58, 'Estado'] = 'Santa Catarina'
df_especies_sem_null.at[58, 'Região'] = 'Sul'

mask = df_especies_sem_null['Nome Comum'].isnull()
df_especies_sem_null[mask]
                   
df_especies_sem_null.at[1105, 'Nome Comum'] = 'Cervo-do-pantanal'
df_especies_sem_null.at[1125, 'Nome Comum'] = 'Morcego esfumaçado'
df_especies_sem_null.at[1128, 'Nome Comum'] = 'Morcego orellha-de-funil'

df_especies_sem_null

In [ ]:
df_desmatamento_filtrado = df_desmatamento[['uc', '2021']]
df_desmatamento_filtrado.rename(columns={'uc': 'Unidade de Conservação Federal'}, inplace=True)
df_desmatamento_filtrado

In [ ]:
df_dados_unificados = pd.merge(df_especies_sem_null, df_desmatamento_filtrado, how='outer', on = 'Unidade de Conservação Federal')
df_dados_unificados